// examples/vue/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView, useRoute } from 'vue-router';

const navItems = [
  { path: '/', label: 'Home' },
  { path: '/interactive', label: 'Interactive' },
  { path: '/themes', label: 'Themes' },
];

const route = useRoute();
</script>

<template>
  <div class="app">
    <nav class="nav">
      <span class="logo">Polygon Background</span>
      <RouterLink
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        :class="{ active: route.path === item.path }"
      >
        {{ item.label }}
      </RouterLink>
    </nav>
    <main class="main">
      <RouterView />
    </main>
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.nav {
  display: flex;
  gap: 1rem;
  padding: 1rem 2rem;
  background: rgba(0, 0, 0, 0.8);
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
}

.logo {
  color: #fff;
  font-weight: bold;
  margin-right: 2rem;
}

.nav a {
  color: #94a3b8;
}

.nav a.active {
  color: #6366f1;
  font-weight: 600;
}

.main {
  flex: 1;
  padding-top: 60px;
}
</style>

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="app">
      <nav class="nav">
        <span class="logo">Polygon Background</span>
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a>
        <a routerLink="/interactive" routerLinkActive="active">Interactive</a>
        <a routerLink="/themes" routerLinkActive="active">Themes</a>
      </nav>
      <main class="main">
        <router-outlet />
      </main>
    </div>
  `,
  styles: [`
    .app {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    .nav {
      display: flex;
      gap: 1rem;
      padding: 1rem 2rem;
      background: rgba(0, 0, 0, 0.8);
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      z-index: 100;
    }
    .logo {
      color: #fff;
      font-weight: bold;
      margin-right: 2rem;
    }
    .nav a {
      color: #94a3b8;
      text-decoration: none;
    }
    .nav a.active {
      color: #6366f1;
      font-weight: 600;
    }
    .main {
      flex: 1;
      padding-top: 60px;
    }
  `],
})
export class AppComponent {}
