// examples/vue/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView, useRoute } from 'vue-router';

const navItems = [
  { path: '/', label: 'Home' },
  { path: '/interactive', label: 'Interactive' },
  { path: '/themes', label: 'Themes' },
];

const route = useRoute();
</script>

<template>
  <div class="app">
    <nav class="nav">
      <span class="logo">Polygon Background</span>
      <RouterLink
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        :class="{ active: route.path === item.path }"
      >
        {{ item.label }}
      </RouterLink>
    </nav>
    <main class="main">
      <RouterView />
    </main>
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.nav {
  display: flex;
  gap: 1rem;
  padding: 1rem 2rem;
  background: rgba(0, 0, 0, 0.8);
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
}

.logo {
  color: #fff;
  font-weight: bold;
  margin-right: 2rem;
}

.nav a {
  color: #94a3b8;
}

.nav a.active {
  color: #6366f1;
  font-weight: 600;
}

.main {
  flex: 1;
  padding-top: 60px;
}
</style>

// examples/react/src/App.tsx
import { Link, Outlet, useLocation } from 'react-router-dom';

const navItems = [
  { path: '/', label: 'Home' },
  { path: '/interactive', label: 'Interactive' },
  { path: '/themes', label: 'Themes' },
];

function App() {
  const location = useLocation();

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <nav style={{
        display: 'flex',
        gap: '1rem',
        padding: '1rem 2rem',
        background: 'rgba(0,0,0,0.8)',
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
      }}>
        <span style={{ color: '#fff', fontWeight: 'bold', marginRight: '2rem' }}>
          Polygon Background
        </span>
        {navItems.map(item => (
          <Link
            key={item.path}
            to={item.path}
            style={{
              color: location.pathname === item.path ? '#6366f1' : '#94a3b8',
              fontWeight: location.pathname === item.path ? 600 : 400,
            }}
          >
            {item.label}
          </Link>
        ))}
      </nav>
      <main style={{ flex: 1, paddingTop: '60px' }}>
        <Outlet />
      </main>
    </div>
  );
}

export default App;
