// examples/vue/src/components/HeroSection.vue
<script setup lang="ts">
import PolygonContainer from './PolygonContainer.vue';
</script>

<template>
  <section class="section">
    <PolygonContainer
      theme="midnight"
      :options="{ pointCount: 100, speed: 0.8 }"
      class="background"
    >
      <div class="content">
        <h1 class="title">Polygon Background</h1>
        <p class="subtitle">
          Beautiful, animated polygon backgrounds for your web applications.
          Built with WebGL and WebAssembly for smooth 60fps performance.
        </p>
        <div class="features">
          <span class="feature">WebGL Rendering</span>
          <span class="feature">WASM Acceleration</span>
          <span class="feature">5 Built-in Themes</span>
          <span class="feature">Mouse Interaction</span>
        </div>
      </div>
    </PolygonContainer>
  </section>
</template>

<style scoped>
.section {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
}

.background {
  width: 100%;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
}

.content {
  position: relative;
  z-index: 1;
  text-align: center;
  padding: 2rem;
  max-width: 800px;
}

.title {
  font-size: 4rem;
  font-weight: 800;
  margin-bottom: 1.5rem;
  background: linear-gradient(135deg, #f8fafc 0%, #94a3b8 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  text-shadow: 0 0 60px rgba(99, 102, 241, 0.5);
}

.subtitle {
  font-size: 1.25rem;
  color: #94a3b8;
  margin-bottom: 2rem;
  line-height: 1.8;
}

.features {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  justify-content: center;
}

.feature {
  padding: 0.5rem 1rem;
  background: rgba(99, 102, 241, 0.2);
  border: 1px solid rgba(99, 102, 241, 0.3);
  border-radius: 9999px;
  font-size: 0.875rem;
  color: #a5b4fc;
}

@media (max-width: 768px) {
  .title {
    font-size: 2.5rem;
  }

  .subtitle {
    font-size: 1rem;
  }
}
</style>

// examples/react/src/components/HeroSection.tsx
import PolygonContainer from './PolygonContainer';
import styles from './HeroSection.module.css';

function HeroSection() {
  return (
    <section className={styles.section}>
      <PolygonContainer
        theme="midnight"
        options={{
          pointCount: 100,
          speed: 0.8,
        }}
        className={styles.background}
      >
        <div className={styles.content}>
          <h1 className={styles.title}>Polygon Background</h1>
          <p className={styles.subtitle}>
            Beautiful, animated polygon backgrounds for your web applications.
            Built with WebGL and WebAssembly for smooth 60fps performance.
          </p>
          <div className={styles.features}>
            <span className={styles.feature}>WebGL Rendering</span>
            <span className={styles.feature}>WASM Acceleration</span>
            <span className={styles.feature}>5 Built-in Themes</span>
            <span className={styles.feature}>Mouse Interaction</span>
          </div>
        </div>
      </PolygonContainer>
    </section>
  );
}

export default HeroSection;
