// examples/vue/src/components/PolygonContainer.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { PolygonBackground, PolygonBackgroundOptions } from 'polygon-background';

interface Props {
  theme?: string;
  options?: Partial<PolygonBackgroundOptions>;
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'midnight',
  options: () => ({}),
});

const containerRef = ref<HTMLDivElement | null>(null);
const instance = ref<PolygonBackground | null>(null);

defineExpose({
  instance,
});

onMounted(() => {
  if (containerRef.value) {
    instance.value = new PolygonBackground(containerRef.value, {
      theme: props.theme,
      ...props.options,
    });
  }
});

onUnmounted(() => {
  instance.value?.destroy();
  instance.value = null;
});

watch(
  () => props.theme,
  (newTheme) => {
    instance.value?.setTheme(newTheme);
  }
);
</script>

<template>
  <div ref="containerRef" class="polygon-container">
    <slot />
  </div>
</template>

<style scoped>
.polygon-container {
  position: relative;
}
</style>

// examples/react/src/components/PolygonContainer.tsx
import { useRef, useEffect, useImperativeHandle, forwardRef } from 'react';
import { PolygonBackground, PolygonBackgroundOptions } from 'polygon-background';

export interface PolygonContainerRef {
  instance: PolygonBackground | null;
}

interface PolygonContainerProps {
  theme?: string;
  options?: Partial<PolygonBackgroundOptions>;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}

const PolygonContainer = forwardRef<PolygonContainerRef, PolygonContainerProps>(
  ({ theme = 'midnight', options = {}, className, style, children }, ref) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const instanceRef = useRef<PolygonBackground | null>(null);

    useImperativeHandle(ref, () => ({
      get instance() {
        return instanceRef.current;
      },
    }));

    useEffect(() => {
      if (!containerRef.current) return;

      instanceRef.current = new PolygonBackground(containerRef.current, {
        theme,
        ...options,
      });

      return () => {
        instanceRef.current?.destroy();
        instanceRef.current = null;
      };
    }, []);

    useEffect(() => {
      if (instanceRef.current) {
        instanceRef.current.setTheme(theme);
      }
    }, [theme]);

    return (
      <div
        ref={containerRef}
        className={className}
        style={{ position: 'relative', ...style }}
      >
        {children}
      </div>
    );
  }
);

PolygonContainer.displayName = 'PolygonContainer';

export default PolygonContainer;
